Use MyRestaurant
insert into TableStatus(Name) values ('Free')
insert into TableStatus(Name) values ('Booked')

insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)
insert into Tables(TableStatusId) values(1)