use MyRestaurant
insert into Drinks(Name,Price,Volume) values('Whiskey Jim Bean',299,0.5)
insert into Drinks(Name,Price,Volume) values('Pepsi',25,0.5)
insert into Drinks(Name,Price,Volume) values('Lemonade',40,1)
insert into Drinks(Name,Price,Volume) values('Tequilla Cuervo Gold',200,0.5)
insert into Drinks(Name,Price,Volume) values('Whiskey Jack Daniel`s',350,0.5)
insert into Drinks(Name,Price,Volume) values('Rum Bacardi',400,0.7)
insert into Drinks(Name,Price,Volume) values('Rum Bacardi',350,0.5)
insert into Drinks(Name,Price,Volume) values('Gin Seagram`s',250,0.5)
insert into Drinks(Name,Price,Volume) values('White Wine Chardonnay',150,0.5)
insert into Drinks(Name,Price,Volume) values('White Wine Moscato',299,0.5)
insert into Drinks(Name,Price,Volume) values('Red Wine Merlot',225,0.5)
insert into Drinks(Name,Price,Volume) values('Red Wine Pinot Noir',249,0.5)
insert into Drinks(Name,Price,Volume) values('Beer Blue Moon',40,0.5)
insert into Drinks(Name,Price,Volume) values('Beer Blunc',50,0.5)