use MyRestaurant
insert into Orders(Date, PersonId) values('5/29/2019',9)
insert into Orders(Date, PersonId) values('5/29/2019',10)
insert into Orders(Date, PersonId) values('5/29/2019',11)
insert into Orders(Date, PersonId) values('5/29/2019',12)
insert into Orders(Date, PersonId) values('5/29/2019',10)

insert into BarOrders(OrderId,DrinkId) values(6,1)
insert into BarOrders(OrderId,DrinkId) values(7,1)
insert into BarOrders(OrderId,DrinkId) values(8,1)
insert into BarOrders(OrderId,DrinkId) values(9,1)
insert into BarOrders(OrderId,DrinkId) values(10,2)
insert into BarOrders(OrderId,DrinkId) values(6,3)
insert into BarOrders(OrderId,DrinkId) values(6,4)
insert into BarOrders(OrderId,DrinkId) values(7,6)
insert into BarOrders(OrderId,DrinkId) values(7,2)
insert into BarOrders(OrderId,DrinkId) values(7,2)
insert into BarOrders(OrderId,DrinkId) values(8,2)
insert into BarOrders(OrderId,DrinkId) values(9,2)
insert into BarOrders(OrderId,DrinkId) values(10,3)
insert into BarOrders(OrderId,DrinkId) values(10,1)
insert into BarOrders(OrderId,DrinkId) values(10,1)

insert into KitchenOrders(OrderId,DishId)values(12,1)
insert into KitchenOrders(OrderId,DishId)values(12,1)
insert into KitchenOrders(OrderId,DishId)values(12,1)
insert into KitchenOrders(OrderId,DishId)values(12,1)
insert into KitchenOrders(OrderId,DishId)values(12,1)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)
insert into KitchenOrders(OrderId,DishId)values(12,2)



